### ISSUE TITLE
画像／リンクの挿入と背景を透過させたい。

### ISSUE THREAD

**Issue by linkevery2s** [code4fukui/input-graph#1]
お疲れ様です。

閃いたことがあります。input-graphを利用させていただこうと思っております。

現在の状況↓
https://humanlink.netlify.app/

ちょっと提案がありますので、こちらに投稿させていただきます。

input-graphタグについて
①背景を透過させたいです。
cssで全く聞かなかったので、JSで制御しているのかな？と思ったのですが、該当箇所が見つけられなかったので、教えてください。

②画像／リンクの挿入とか出来たりしませんか？
マインドマップ的な使い方も面白いかなと思ってまして、画像やリンク貼れると面白いなと思った次第です。

よろしくお願いします。

**Comment by taisukef** [comment]
活用ありがとうございます

現状、canvasをベースにしているのでCSSは効きません
https://github.com/code4fukui/input-graph/blob/main/CanvasElement.js
透過させる仕様もおもしろそうですね

canvasを使わないDOM+SVGにすると画像やリンクなどHTMLを自由に入れられて便利かもしれませんね
画像とリンクだけなど決まった形なら今のcanvas版の改造でも良さそうです

**Comment by linkevery2s** [comment]
承知しました！色々といじってみます！
